apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moodle.fullname" . }}-env
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
data:
  MOODLE_URL: "https://{{ .Values.gateway.hostname }}"
  MOODLE_SSLPROXY: "true"
  MOODLE_DB_TYPE: "pgsql"
  MOODLE_DB_SSLMODE: {{ .Values.postgresql.sslmode | quote }}
  {{- if .Values.redis.enabled }}
  MOODLE_REDIS_HOST: {{ include "moodle.redisHost" . | quote }}
  MOODLE_REDIS_PORT: {{ .Values.redis.service.port | quote }}
  {{- end }}
  PHP_MEMORY_LIMIT: {{ .Values.moodle.php.memoryLimit | quote }}
  PHP_MAX_EXECUTION_TIME: {{ .Values.moodle.php.maxExecutionTime | quote }}
